module.exports = {
    // allow header
    "origins": "*",
    "log": true,
    "heartbeats": true,
    "resource": "/socket.io",
    "authorization": false,
    "blacklist": ["disconnect"],
    "log level": 2,
    "close timeout": 60,
    "heartbeat interval": 25,
    "heartbeat timeout": 60,
    "polling duration": 20,
    "flash policy server": true,
    "flash policy port": 10843,
    "destroy upgrade": true,
    "destroy buffer size": 10E7,
    "browser client": true,
    "browser client cache": true,
    "browser client minification": false,
    "browser client etag": false,
    "browser client expires": 315360000,
    "browser client gzip": false,
    "browser client handler": false,
    "client store expiration": 15,
    "match origin protocol": false,
}